import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {interiorCatalogue,type InteriorObjectId} from './interior-catalogue';
import {interiorObject,type ObjectMaterial} from './interior-objects';
import {refineSurface} from '../rendering/surfaces';
const mount=document.getElementById('object-stage')!,caption=document.getElementById('object-caption')!,select=document.getElementById('object-choice') as HTMLSelectElement;
const renderer=new T.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;mount.append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#d9d5c6');const camera=new T.PerspectiveCamera(38,innerWidth/innerHeight,.015,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=.08;
scene.add(new T.HemisphereLight('#fff2dc','#746957',2.4));const sun=new T.DirectionalLight('#fff0d7',3.2);sun.position.set(-3,6,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-3,right:3,top:3,bottom:-3,near:.1,far:20});sun.shadow.normalBias=.007;scene.add(sun);const fill=new T.DirectionalLight('#d3e0eb',1);fill.position.set(3,2,-3);scene.add(fill);
const ground=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshStandardMaterial({color:'#c6c1ad',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.002;ground.receiveShadow=true;scene.add(ground);
const colours:Record<ObjectMaterial,string>={oak:'#826449',darkwood:'#4e3926',iron:'#292b28',steel:'#93978e',copper:'#b3844a',cream:'#dfd5b9',blue:'#344d73',clay:'#865033',cloth:'#69785f',green:'#535d3d',coal:'#24241d',glass:'#789186',lampglass:'#d9e0d3',paper:'#d1c7ab',linen:'#d0c7ae',tile:'#755038',stone:'#807b69'};
const materials=Object.fromEntries(Object.entries(colours).map(([key,color])=>{const m=new T.MeshStandardMaterial({color,roughness:['steel','copper','cream','blue','glass'].includes(key)?.40:.95,metalness:['iron','steel','copper'].includes(key)?.55:0,vertexColors:['tile','stone'].includes(key),side:key==='cloth'?T.DoubleSide:T.FrontSide});if(key==='lampglass'){m.transparent=true;m.opacity=.20;m.depthWrite=false;m.roughness=.12;m.side=T.DoubleSide;}refineSurface(m,key==='oak'||key==='darkwood'?'wood':key==='cloth'?'cloth':key==='clay'||key==='cream'||key==='blue'?'ceramic':key==='paper'?'plaster':key==='glass'?'glass':'iron');return [key,m];})) as Record<ObjectMaterial,T.Material>;
const group=new T.Group();scene.add(group);
function show(id:InteriorObjectId){group.clear();const asset=interiorObject(id);for(const p of asset.parts){const mesh=new T.Mesh(p.geometry,materials[p.material]);mesh.castShadow=p.material!=='lampglass';mesh.receiveShadow=true;group.add(mesh);}const size=asset.bounds.getSize(new T.Vector3()),center=asset.bounds.getCenter(new T.Vector3()),distance=Math.max(size.x,size.y,size.z)*2.6;
 camera.position.copy(center).add(new T.Vector3(distance*.67,distance*.45,distance));controls.target.copy(center);controls.update();select.value=id;caption.textContent=interiorCatalogue.find(p=>p[0]===id)![1]+' · '+size.toArray().map(v=>v.toFixed(2)).join(' × ')+' m';mount.dataset.object=id;history.replaceState(null,'','?item='+id);}
select.onchange=()=>show(select.value as InteriorObjectId);for(const [name,dir]of [['object-prev',-1],['object-next',1]] as const)document.getElementById(name)!.onclick=()=>show(interiorCatalogue[(select.selectedIndex+dir+interiorCatalogue.length)%interiorCatalogue.length][0]);const initial=new URLSearchParams(location.search).get('item');show(interiorCatalogue.find(p=>p[0]===initial)?.[0]??'oven-range');renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
